version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      DATABASE_URL: $DATABASE_URL
      ALIVE_NAME: $ALIVE_NAME
      BOT_TOKEN: $BOT_TOKEN
      HANDLER: $HANDLER
      LEGEND_STRING: $LEGEND_STRING
      SPAM: $SPAM
      TZ: $TZ
      UPSTREAM_REPO: $UPSTREAM_REPO
